[theme]
base = "light"
primaryColor = "#D71920"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9FC"
textColor = "#17243A"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 100

[browser]
gatherUsageStats = false
